/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArrowIcon: typeof import('./src/components/patient/ArrowIcon.vue')['default']
    BaseButton: typeof import('./src/components/patient/BaseButton.vue')['default']
    Button: typeof import('./src/components/patient/button.vue')['default']
    copy: typeof import('./src/components/patient/Title copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Step: typeof import('./src/components/patient/Step.vue')['default']
    Steps: typeof import('./src/components/patient/Steps.vue')['default']
    Title: typeof import('./src/components/patient/Title.vue')['default']
  }
}
