/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArrowIcon: typeof import('./src/components/patient/ArrowIcon.vue')['default']
    BaseButton: typeof import('./src/components/patient/BaseButton.vue')['default']
    DrawingBoard: typeof import('./src/components/DrawingBoard.vue')['default']
    DrawingBoardN: typeof import('./src/components/DrawingBoardN.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Steps: typeof import('./src/components/patient/Steps.vue')['default']
    Title: typeof import('./src/components/patient/Title.vue')['default']
  }
}
